### ISSUE TITLE
Reporte de practica de TextBox

### ISSUE THREAD

**Issue by JazminloRI** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-JazminloRI#2]
[Reporte de practica de TexBox.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-JazminloRI/files/6348369/Reporte.de.practica.de.TexBox.pdf)

**Comment by Yeim1129** [comment]
EVALUACION: 19.0% 
EVALUÒ: JOSE MANUEL HERNANDEZ
[Rúbrica reporte de practica TextBox_Jazmín López.docx](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-JazminloRI/files/6360046/Rubrica.reporte.de.practica.TextBox_Jazmin.Lopez.docx)

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado.
